### ISSUE TITLE
File is only added to history when leaving the buffer

### ISSUE THREAD

**Issue by smjonas** [smartpde/telescope-recent-files#2]
Hey, first of all thanks for this great plugin! This is definitely an improvement over the default Telescope `oldfiles` (btw, did you consider contributing this to the telescope repository directly?).

I don't know why, but for me when I enter a new file that's not at the top of the list of recent files it is not added until I leave the buffer. See this recording (sorry for the flicker :smile:):

![recent_files](https://user-images.githubusercontent.com/40792180/189108684-522b4539-3b25-4eed-8f63-24e52f05db3e.gif)

Here, the `vimwiki.vim` file is only added after I leave the buffer.

**Comment by defr0std** [comment]
Hi, (and thanks),  

This happens because the file in the current window is not displayed in the picker. When you change to another file, then the previous one is displayed at the top and so on. There is really no need to display the current file at the top, because you already have it open. So you would always need to skip one entry in the picker yourself for doing anything useful.

If I remember correctly, built-in Telescope's  picker behaves similarly, although I would need to double check. 

P.S. Regarding contribution to Telescope itself, I think most of the options in this plugin are quite reasonable, maybe except for transform_file_path which is needed for my rather degenerate use case... I could ask in the Telescope's repo if they would be interested.

**Comment by smjonas** [comment]
Oh, that makes a lot of sense - thank you! 

> Regarding contribution to Telescope itself, I think most of the options in this plugin are quite reasonable

That would be great, including open files in the list of old files seems like a good default to me. I'm sure they would accept it (if not as a default, at least as an option) :)
